In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = '/content/drive/My Drive/kaggle'

In [3]:
%cd /content/drive/My Drive/kaggle

/content/drive/My Drive/kaggle


In [4]:
!kaggle datasets download -d pankeshpatel/homepricesmultiplevariables

  0% 0.00/252 [00:00<?, ?B/s]
100% 252/252 [00:00<00:00, 44.6kB/s]


In [5]:
!unzip \*.zip && rm *.zip

Archive:  archive (6).zip
  inflating: homeprices.csv          

Archive:  homepricesmultiplevariables.zip
replace homeprices.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: homeprices.csv          

2 archives were successfully processed.


In [6]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import statistics as st
import math
import warnings
warnings.filterwarnings('ignore')

In [9]:
df = pd.read_csv("/content/drive/My Drive/kaggle/homeprices.csv")
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [10]:
import sklearn


In [11]:
from sklearn import linear_model

In [13]:
median = df.median()
median

area          3400.0
bedrooms         4.0
age             16.5
price       602500.0
dtype: float64

In [18]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [22]:
model = linear_model.LinearRegression()
model.fit(df.drop('price',axis = 'columns'),df.price)

LinearRegression()

In [25]:
model.predict([[3000,4,40]])

array([521797.13165825])

In [26]:
model.predict([[2500,4,5]])

array([578876.03748933])

In [27]:
model.coef_ 

array([  112.06244194, 23388.88007794, -3231.71790863])

it is returning coefficients for area , bedrooms and age respectively

In [29]:
model.intercept_


221323.00186540396